//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : BaseSvgObject.h
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#if !defined(_BASESVGOBJECT_H)
#define _BASESVGOBJECT_H

#include <QDomElement>
#include <QPainter>
#include "SvgObjectType.h"

class BaseSvgObject
{
protected:
	int m_width;
	int m_height;
	bool m_fill;
	int m_stroke;
	int m_strokeWidth;
	SvgObjectType m_type;
	float m_xFactor;
	float m_yFactor;
public:
	BaseSvgObject();
	virtual ~BaseSvgObject();
	virtual void Parse(QDomElement &element) = 0;
	virtual QString toString() = 0;
	virtual void render(QPainter *canvas) = 0;
	int getWidth();
	int getHeight();
	bool IsFill();
	void getStroke();
	int getStrookeWidth();
	SvgObjectType getType();
	void setXFactor(float xFactor);
	void setYFactor(float yFactor);
};

#endif  //_BASESVGOBJECT_H
