//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : BaseSvgObject.cpp
//  @ Date : 3/25/2013
//  @ Author : 
//
//



#include "BaseSvgObject.h"

BaseSvgObject::BaseSvgObject()
{
	m_xFactor = m_yFactor = 1.0;
}

BaseSvgObject::~BaseSvgObject()
{

}


int BaseSvgObject::getWidth()
{
	return m_width;
}

int BaseSvgObject::getHeight()
{
	return m_height;
}

bool BaseSvgObject::IsFill()
{
	return false;
}

void BaseSvgObject::getStroke()
{
	
}

int BaseSvgObject::getStrookeWidth()
{
	return m_strokeWidth;
}

SvgObjectType BaseSvgObject::getType()
{
	return SvgObjectType::UnknownSvg;
}

void BaseSvgObject::setXFactor( float xFactor )
{
	m_xFactor = xFactor;
}

void BaseSvgObject::setYFactor( float yFactor )
{
	m_yFactor = yFactor;
}


