//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : EllipseSvgObject.h
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#if !defined(_ELLIPSESVGOBJECT_H)
#define _ELLIPSESVGOBJECT_H

#include <QPoint>
#include "BaseSvgObject.h"

class EllipseSvgObject : public BaseSvgObject
{
protected:
	int m_centerX;
	int m_centerY;
	int m_radiusX;
	int m_radiusY;
public:
	EllipseSvgObject();
	virtual ~EllipseSvgObject();

	QPoint getCenter();
	int getXRadius();
	int getYRadius();
	void Parse(QDomElement &element);
	void render(QPainter* canvas); 	
	QString toString();
};

#endif  //_ELLIPSESVGOBJECT_H
