//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : FactorySvgObjects.cpp
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#include "FactorySvgObjects.h"
#include "LineSvgObject.h"
#include "RectSvgObject.h"
#include "EllipseSvgObject.h"
#include "PolygonSvgObject.h"


BaseSvgObject* FactorySvgObjects::CreateSvgObject(QDomElement &domElement)
{
	BaseSvgObject* object = NULL;
	QString name = domElement.tagName().toLower();
	if (name == "line")
	{
		object = new LineSvgObject();
	}
	else if(name == "rect")
	{
		object = new RectSvgObject();
	}
	else if(name == "ellipse") 
	{
		object = new EllipseSvgObject();
	}
	else if(name == "polygon")
	{
		object = new PolylineSvgObject();
	}
	if(object != NULL)
		object->Parse(domElement);
	return object;
}

