//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : LineSvgObject.h
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#if !defined(_LINESVGOBJECT_H)
#define _LINESVGOBJECT_H
#include <QPoint>
#include "BaseSvgObject.h"

class LineSvgObject : public BaseSvgObject
{
protected:
	int m_x1;
	int m_y1;
	int m_x2;
	int m_y2;
public:
	LineSvgObject();
	virtual ~LineSvgObject();

	QPoint getStartPoint();
	QPoint getEndPoint();
	void Parse(QDomElement &element);
	void render(QPainter *canvas);
	QString toString();
};

#endif  //_LINESVGOBJECT_H
