//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : LineSvgObject.cpp
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#include "LineSvgObject.h"


LineSvgObject::LineSvgObject()
{
	m_type = SvgObjectType::LineSvg;
}

LineSvgObject::~LineSvgObject()
{

}

QPoint LineSvgObject::getStartPoint()
{
	return QPoint(m_x1 * m_xFactor,m_y1 * m_yFactor);
}

QPoint LineSvgObject::getEndPoint()
{
	return QPoint(m_x2 * m_xFactor,m_y2 * m_yFactor);
}

void LineSvgObject::Parse(QDomElement &element)
{
	QDomNamedNodeMap mapAttr = element.attributes();
	for(int i = 0; i < mapAttr.count();i++)
	{
		QDomAttr attr = mapAttr.item(i).toAttr();
		if(attr.isNull())
			continue;
		if(attr.name() == "x1")
			m_x1 = attr.value().toInt();
		else if(attr.name() == "y1")
			m_y1 = attr.value().toInt();
		else if(attr.name() == "x2")
			m_x2 = attr.value().toInt();
		else if(attr.name() == "y2")
			m_y2 = attr.value().toInt();
	}
}

QString LineSvgObject::toString()
{
	return QString("x1=%1 y1=%2 x2=%3 y2=%4").arg(m_x1).arg(m_y1).arg(m_x2).arg(m_y2);
}

void LineSvgObject::render(QPainter *canvas)
{
	canvas->drawLine(getStartPoint(),getEndPoint());
}