//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : RectSvgObject.h
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#if !defined(_RECTSVGOBJECT_H)
#define _RECTSVGOBJECT_H

#include <QPoint>
#include "BaseSvgObject.h"

class RectSvgObject : public BaseSvgObject
{
protected:
	int m_x;
	int m_y;
	int m_widthRect;
	int m_heightRect;
public:
	RectSvgObject();
	virtual ~RectSvgObject();

	QPoint getPoint();
	int getRectWidth();
	int getRectHeight();
	void Parse(QDomElement &element);
	void render(QPainter *canvas);
	QString toString();
};

#endif  //_RECTSVGOBJECT_H
