//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : SvgObjectContainer.cpp
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#include "SvgObjectContainer.h"
#include "BaseSvgObject.h"

BaseSvgObject* SvgObjectContainer::getObject(int index)
{
	return !m_listObjects.empty() && index < m_listObjects.size() ? m_listObjects.at(index) : NULL;
}

void SvgObjectContainer::addObject(BaseSvgObject *object)
{
	if(object == NULL)
		return;
	m_listObjects.push_back(object);
}

