//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : SvgObjectType.h
//  @ Date : 3/25/2013
//  @ Author : 
//
//


#if !defined(_SVGOBJECTTYPE_H)
#define _SVGOBJECTTYPE_H


enum SvgObjectType
{
	UnknownSvg,
	LineSvg,
	RectSvg,
	EllipseSvg,
	PolygonSvg
};

#endif  //_SVGOBJECTTYPE_H
