//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : baseportcreator.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_BASEPORTCREATOR_H)
#define _BASEPORTCREATOR_H

#include "baseport.h"
#include "porttype.h"

class BasePortCreator
{
public:
	virtual BasePort* Create(PortType type, QString filename) = 0;
};

#endif  //_BASEPORTCREATOR_H
