//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : baseport.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_BASEPORT_H)
#define _BASEPORT_H

#include <QtCore/QObject>
#include <QtSerialPort/QSerialPort>
#include "portsettingsreader.h"
#include <QtCore/QQueue>

#define DEFAULT_LENGHT 2
#define DEFAULT_TIMEOUT 25


class BasePort : public QObject
{
	Q_OBJECT

public:
	BasePort();
	virtual ~BasePort();

	bool init();
	virtual bool write(QByteArray data) = 0;
	virtual QByteArray read(int max_size = -1) = 0;
	virtual void setPort(QString& port);
	virtual int getBufferSize() const;
	virtual void setBufferSize(int size);

signals:
	void readyRead();

private slots:
	void readReadyData();

private:
	QString m_tempData;

	void findCommands();

protected:
	PortSettingsReader m_PortSettingsReader;
	QString m_fileName;
	QSerialPort m_port;
	bool m_Ready;
	int m_BufferSize;
	QQueue<QString> m_queue;


	virtual void readSettings();
	virtual bool initPort();
	
};

#endif  //_BASEPORT_H
