//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : portsettings.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_PORTSETTINGS_H)
#define _PORTSETTINGS_H

#include <QtCore/qiodevice.h>

class PortSettings
{
public:
	void setIOMode(QIODevice::OpenMode mode);
	void setRate(int rate);
	void setDataBits(int dataBits);
	void setParity(int parity);
	void setStopBits(int stopBits);
	void setFlowControl(int flowControl);
	void setPort(QString& port);
	QIODevice::OpenMode getIOMode() const;
	int getRate() const;
	int getDataBits() const;
	int getParity() const;
	int getStopBits() const;
	int getFlowControl() const;
	QString getPort() const;
private:
	QIODevice::OpenMode m_IOMode;
	int m_Rate;
	int m_DataBits;
	int m_Parity;
	int m_StopBits;
	int m_FlowControl;
	QString m_Port;
};

#endif  //_PORTSETTINGS_H
