//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : porttype.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_PORTTYPE_H)
#define _PORTTYPE_H


enum PortType
{
	Usb,
	Com
};

#endif  //_PORTTYPE_H
