//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : portsettingsreader.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_PORTSETTINGSREADER_H)
#define _PORTSETTINGSREADER_H

#include <QtXml/QDomDocument>

#include "portsettings.h"

#define PORTSETTINGS		"portsettings" // root element

// child elements
#define MODE				"mode"
#define RATE				"rate"
#define DATABITS			"databits"
#define PARITY				"parity"
#define STOPBITS			"stopbits"
#define FLOWCONTROL			"flowcontrol"
#define PORT				"port"

#define VALUE				"value"


class PortSettingsReader
{
public:
	PortSettingsReader();
	PortSettingsReader(QString filename);
	~PortSettingsReader();

	void readSettings();
	void readSettings(QString filname);
	const PortSettings* getSettings();
private:
	bool  m_isReady;

	QString m_Filename;
	QDomDocument m_QDomDocument;
	PortSettings *m_PortSettings;

	void parseSettings(QIODevice *device);
	void parse(QDomElement *root);
};

#endif  //_PORTSETTINGSREADER_H
