//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : portsettings.cpp
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#include "portsettings.h"

void PortSettings::setIOMode(QIODevice::OpenMode mode)
{
	m_IOMode = mode;
}

void PortSettings::setRate(int rate)
{
	m_Rate = rate;
}

void PortSettings::setDataBits(int dataBits)
{
	m_DataBits = dataBits;
}

void PortSettings::setParity(int parity)
{
	m_Parity = parity;
}

void PortSettings::setStopBits(int stopBits)
{
	m_StopBits = stopBits;
}

void PortSettings::setFlowControl(int flowControl)
{
	m_FlowControl = flowControl;
}

QIODevice::OpenMode PortSettings::getIOMode() const
{
	return m_IOMode;
}

int PortSettings::getRate() const
{
	return m_Rate;
}

int PortSettings::getDataBits() const
{
	return m_DataBits;
}

int PortSettings::getParity() const
{
	return m_Parity;
}

int PortSettings::getStopBits() const
{
	return m_StopBits;
}

int PortSettings::getFlowControl() const
{
	return m_FlowControl;
}

void PortSettings::setPort( QString& port )
{
	m_Port = port;
}

QString PortSettings::getPort() const
{
	return m_Port;
}

