//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : serialportcreator.cpp
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#include "serialportcreator.h"
#include "baseport.h"
#include "porttype.h"
#include "usbport.h"

BasePort* SerialPortCreator::Create(PortType type, QString filename)
{
	BasePort *port = NULL;
	switch(type)
	{
	case Usb:
		port = new UsbPort(filename);
		break;
	}
	return port;
}

