//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : serialportcreator.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_SERIALPORTCREATOR_H)
#define _SERIALPORTCREATOR_H

#include "baseportcreator.h"
#include "baseport.h"
#include "porttype.h"

class SerialPortCreator : public BasePortCreator
{
public:
	BasePort* Create(PortType type, QString filename);
};

#endif  //_SERIALPORTCREATOR_H
