//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : usbport.cpp
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#include "usbport.h"


UsbPort::UsbPort(QString filename)
{
	m_fileName = filename;
}

UsbPort::~UsbPort()
{

}

bool UsbPort::write(QByteArray data)
{
	if(!m_Ready)
		return false;
	return m_port.write(data);
}

QByteArray UsbPort::read(int max_size)
{
	if(!m_Ready)
		return QByteArray();
	QByteArray res;
	QString temp = m_queue.dequeue() + ";";
	res = temp.toLocal8Bit();
	return res;

}

