//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Core Model
//  @ File Name : usbport.h
//  @ Date : 4/12/2013
//  @ Author : 
//
//


#if !defined(_USBPORT_H)
#define _USBPORT_H

#include "baseport.h"

class UsbPort : public BasePort
{
public:
	UsbPort(QString filename);
	virtual ~UsbPort();

	bool write(QByteArray data) override; 
	QByteArray read(int max_size = -1) override; 
	
};

#endif  //_USBPORT_H
